// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSey7-pNbcPX3BpK7kwTGc-GpzBdtyy0',
    appId: '1:1096605823866:web:cf31adcfebbc10c86d9cc3',
    messagingSenderId: '1096605823866',
    projectId: 'kittiechat-24ee2',
    authDomain: 'kittiechat-24ee2.firebaseapp.com',
    storageBucket: 'kittiechat-24ee2.appspot.com',
    measurementId: 'G-P5B7NB84M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhXbyzlORhizW9N393xgiD94LgB9UCEeo',
    appId: '1:1096605823866:android:bf21927ddde7e3af6d9cc3',
    messagingSenderId: '1096605823866',
    projectId: 'kittiechat-24ee2',
    storageBucket: 'kittiechat-24ee2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqCbfCPB6aC7wQNnivnhrVo1Lh5lYBBdY',
    appId: '1:1096605823866:ios:d2b2ca91cfa07d466d9cc3',
    messagingSenderId: '1096605823866',
    projectId: 'kittiechat-24ee2',
    storageBucket: 'kittiechat-24ee2.appspot.com',
    androidClientId: '1096605823866-djmdpvcaom79p93k96p55nj107fm6vhi.apps.googleusercontent.com',
    iosClientId: '1096605823866-7cj6jj63qdl5c7ib9tvc33espmlhbjua.apps.googleusercontent.com',
    iosBundleId: 'com.example.kittieChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqCbfCPB6aC7wQNnivnhrVo1Lh5lYBBdY',
    appId: '1:1096605823866:ios:f3614192435f69fe6d9cc3',
    messagingSenderId: '1096605823866',
    projectId: 'kittiechat-24ee2',
    storageBucket: 'kittiechat-24ee2.appspot.com',
    androidClientId: '1096605823866-djmdpvcaom79p93k96p55nj107fm6vhi.apps.googleusercontent.com',
    iosClientId: '1096605823866-4i3l402a74u8qubcd5jjm3uen1b0hul6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kittieChat.RunnerTests',
  );
}
